// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTNmvH658uBQUTP8eZCOBX3jb0-IXbPo',
    appId: '1:761350834689:web:7d83789f7aef7a77044e00',
    messagingSenderId: '761350834689',
    projectId: 'taxibookingpuna',
    authDomain: 'taxibookingpuna.firebaseapp.com',
    databaseURL: 'https://taxibookingpuna-default-rtdb.firebaseio.com',
    storageBucket: 'taxibookingpuna.appspot.com',
    measurementId: 'G-BPSJ8RG4X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdct76m7O7Rttg5gadnr29wkXEJKZkZLc',
    appId: '1:761350834689:android:d65b3de205169784044e00',
    messagingSenderId: '761350834689',
    projectId: 'taxibookingpuna',
    databaseURL: 'https://taxibookingpuna-default-rtdb.firebaseio.com',
    storageBucket: 'taxibookingpuna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_uyKFvfshPfjRRKrovE0DvXj2sK8a4E',
    appId: '1:761350834689:ios:90869817246303a0044e00',
    messagingSenderId: '761350834689',
    projectId: 'taxibookingpuna',
    databaseURL: 'https://taxibookingpuna-default-rtdb.firebaseio.com',
    storageBucket: 'taxibookingpuna.appspot.com',
    iosBundleId: 'com.vyaparify.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_uyKFvfshPfjRRKrovE0DvXj2sK8a4E',
    appId: '1:761350834689:ios:90869817246303a0044e00',
    messagingSenderId: '761350834689',
    projectId: 'taxibookingpuna',
    databaseURL: 'https://taxibookingpuna-default-rtdb.firebaseio.com',
    storageBucket: 'taxibookingpuna.appspot.com',
    iosBundleId: 'com.vyaparify.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaTNmvH658uBQUTP8eZCOBX3jb0-IXbPo',
    appId: '1:761350834689:web:3a2e42c027db6061044e00',
    messagingSenderId: '761350834689',
    projectId: 'taxibookingpuna',
    authDomain: 'taxibookingpuna.firebaseapp.com',
    databaseURL: 'https://taxibookingpuna-default-rtdb.firebaseio.com',
    storageBucket: 'taxibookingpuna.appspot.com',
    measurementId: 'G-NDS8YZP90F',
  );
}
